### ISSUE TITLE
ChannelUp, ChannelDown and others actions doesn't work

### ISSUE THREAD

**Issue by Etharr** [primaeval/plugin.video.pvr.plugin.player#1]
I'm using your addon and I encountered annoying issue.
None of specyfic for PVR actions doesn't work.

**Comment by primaeval** [comment]
They won't. This addon is really a trick to allow you to use the streams from other addons in the PVR.
It plays the addon streams as if you have clicked them from their own addon.

There might be a way to redirect the stream urls back into the PVR like normal in a future version of Kodi but it won't work right now. 

The closest you can get at the moment is to see what the urls are in the kodi.log and add them to the IPTV Simple Client m3u file. That won't help with addons that constantly change their url.

This is the closest you will get to being able to integrate the PVR and addon streams that I know of so far.

**Comment by Etharr** [comment]
I see. Maybe you should consider other solution. Based on this:
https://github.com/kodinerds/repo/tree/master/service.iptv.proxy

**Comment by primaeval** [comment]
That addon is specific to 4 iptv services. This addon works for any addon. 
That one uses the redirect that I was talking about, which is good, but you need to make a player for every service you use. 
If you can do that for the services you use you should use that one. 
If you want to access other addons and don't know how to code you should use this one. 
If you can figure out the urls for the streams you need from the log you should just make an m3u file.
